name: Branch Deleted OWHH
on: delete
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run notification
        run: |
          echo "esto correra ?"
          echo "repo ${{ github.event.ref }}"
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"
